version: '3.8'

services:
  orders-service:
    build:
      context: ./itq/orders-service
      depends_on:
        db-orders:
          condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - itq-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-orders:5432/itq-orders-database
      SPRING_DATASOURCE_USERNAME: itq-user
      SPRING_DATASOURCE_PASSWORD: itq-password
  number-service:
    build:
      context: ./itq/numbers-service
      depends_on:
        db-numbers:
          condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - itq-network
  db-orders:
    image: postgres:15
    environment:
      POSTGRES_DB: itq-orders-database
      POSTGRES_USER: itq-user
      POSTGRES_PASSWORD: itq-password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "itq-user" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - orders_data:/data/db
    networks:
      - my-network
  db-numbers:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGODB_URI: mongodb://db-numbers:27017/itq-numbers-database
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - numbers_data:/data/db
    networks:
      - itq-network
networks:
  itq-network:
volumes:
  orders-data:
  numbers-data:



#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
