spring:
  application:
    name: itq-orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/itq-orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
---
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
---
springdoc:
  api-docs:
    yaml: true