spring:
  application:
    name: itq-orders-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/itq-orders}
    username: ${SPRING_DATASOURCE_USER:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
---
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
---
springdoc:
  api-docs:
    yaml: true
---
itq:
  numbers-service:
    url: ${SPRING_DATASOURCE_HOST:localhost}
    port: 8081