spring:
  application:
    name: itq-orders-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/itq-orders}
    username: ${SPRING_DATASOURCE_USER:itq-user}
    password: ${SPRING_DATASOURCE_PASSWORD:itq-password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
---
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG
    org.apache.wicket: DEBUG
    org.apache.wicket.protocol.http: WARN
    org.apache.wicket.request: WARN
    org.apache.wicket.protocol.http.WicketFilter: DEBUG
---

---
springdoc:
  api-docs:
    yaml: true
---
itq:
  numbers-service:
    url: ${SPRING_DATASOURCE_HOST:localhost}
    port: 8081