spring:
  application:
    name: itq-orders-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-orders:5432/itq-orders-database}
    username: ${SPRING_DATASOURCE_USERNAME:itq-user}
    password: ${SPRING_DATASOURCE_PASSWORD:itq-password}
    driver-class-name: org.postgresql.Driver
---
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
---
springdoc:
  api-docs:
    yaml: true
---
itq:
  numbers-service:
    url: ${ITQ_NUMBERS_HOST:localhost}
    port: 8081